services:
  frontend:
    build:
      context: ./frontend-js  # Ensure this points to the frontend folder
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend-js:/app
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8080

  backend:
    build:
      context: ./backend-go  # Ensure correct context
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./backend-go:/app
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/icord
    depends_on:
      db:
        condition: service_healthy
    # command: ["sh", "-c", "sleep infinity"]  # Override CMD to keep the container running
  db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    env_file:   # ✅ Load environment variables from .env
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck: # ✅ Fixed indentation
      test: ["CMD-SHELL", "pg_isready -U user -d icord"]
      interval: 5s
      retries: 5
      timeout: 3s

volumes:
  db_data: